# Generated by Django 5.1.6 on 2025-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('password1', models.CharField(max_length=20, verbose_name='Confirm your password')),
            ],
        ),
    ]
